Improvements to WilsonGaugeAction deriv function
UCL-ARC/Grid pull request #16
Opened 2024-12-16 16:38 UTC by qiUip

Moved the loop to create the vector of the `GaugeLinkField` to outside `WilsonLoops<Gimpl>::Staple()` so it only needs to `PeekIndex` once per `deriv` and avoid redundantly creating it once for each direction.

Additionally, changed a few variable names and formatting that align with `deriv` for consistency and readability.

2025-01-13 13:46 UTC, asifsamiarain commented
As Tursa is on maintenance this week so tried to test the code at cosma8's CPU with the help of `gcc-14.1.0` and `openmpi-4.1.5` and it looks working satisfactorily:

`develop` branch:

```
[dc-asif1@login8b pgda011]$ mlc gdchk defa00
                                                                        LOG_NAME             SEC                 Plaquette      NODES
                   gd_cosma8-gnu_seq-001_sp2n-8.8.8.8-1.1.1.1_defa00_7689408.log       28.992883        0.2815070424670782      m8226
                   gd_cosma8-gnu_seq-002_sp2n-8.8.8.8-1.1.1.1_defa00_7689409.log       17.140950         0.281507042467078      m8227
                   gd_cosma8-gnu_seq-004_sp2n-8.8.8.8-1.1.1.1_defa00_7689410.log       10.652088        0.2815070424670779      m8228
                   gd_cosma8-gnu_seq-008_sp2n-8.8.8.8-1.1.1.1_defa00_7689412.log        9.866800        0.2815070424670778      m8250
                   gd_cosma8-gnu_seq-016_sp2n-8.8.8.8-1.1.1.1_defa00_7689413.log        9.146011        0.2815070424670778      m8251
                   gd_cosma8-gnu_seq-032_sp2n-8.8.8.8-1.1.1.1_defa00_7689414.log        9.836240        0.2815070424670778      m8225
                   gd_cosma8-gnu_seq-064_sp2n-8.8.8.8-1.1.1.1_defa00_7689415.log       15.152011        0.2815070424670778      m8257
                   gd_cosma8-gnu_seq-128_sp2n-8.8.8.8-1.1.1.1_defa00_7689416.log       34.612771        0.2815070424670779      m8086
```


`gauge_action_deriv` branch:

```
[dc-asif1@login8b pgda012]$ mlc gdchk defa00
                                                                        LOG_NAME             SEC                 Plaquette      NODES
                   gd_cosma8-gnu_seq-001_sp2n-8.8.8.8-1.1.1.1_defa00_7689434.log       27.154192        0.2815070424670782      m8226
                   gd_cosma8-gnu_seq-002_sp2n-8.8.8.8-1.1.1.1_defa00_7689435.log       16.373990         0.281507042467078      m8227
                   gd_cosma8-gnu_seq-004_sp2n-8.8.8.8-1.1.1.1_defa00_7689436.log       10.212848        0.2815070424670779      m8228
                   gd_cosma8-gnu_seq-008_sp2n-8.8.8.8-1.1.1.1_defa00_7689437.log        8.884185        0.2815070424670778      m8250
                   gd_cosma8-gnu_seq-016_sp2n-8.8.8.8-1.1.1.1_defa00_7689438.log        8.641423        0.2815070424670778      m8251
                   gd_cosma8-gnu_seq-032_sp2n-8.8.8.8-1.1.1.1_defa00_7689439.log        9.775949        0.2815070424670778      m8225
                   gd_cosma8-gnu_seq-064_sp2n-8.8.8.8-1.1.1.1_defa00_7689440.log       15.347893        0.2815070424670778      m8257
                   gd_cosma8-gnu_seq-128_sp2n-8.8.8.8-1.1.1.1_defa00_7689441.log       33.966997        0.2815070424670779      m8086

```

2025-01-24 16:43 UTC, asifsamiarain commented
As the Tursa is back after maintenance, so synched the develop branch and tested bigger grid w.r.t. GPU:

```
develop branch:
[dc-asif1@tursa-login2 pgda016]$ mlc gdchk defe
                                                                        LOG_NAME             SEC                 Plaquette      NODES
               gd_tursa-gnucuda_seq-001_su3-24.24.24.48-1.1.1.1_defe00_44457.log      395.436031        0.2558495317751736 tu-c0r0n87
               gd_tursa-gnucuda_seq-001_su3-24.24.24.48-1.1.1.1_defe01_44458.log     3239.503169        0.4949517921780855 tu-c0r0n87

gauge_action_deriv branch:
[dc-asif1@tursa-login2 pgda017]$ mlc gdchk defe
                                                                        LOG_NAME             SEC                 Plaquette      NODES
               gd_tursa-gnucuda_seq-001_su3-24.24.24.48-1.1.1.1_defe00_44460.log      316.656489        0.2558495317751736 tu-c0r0n90
               gd_tursa-gnucuda_seq-001_su3-24.24.24.48-1.1.1.1_defe01_44481.log     2611.649632        0.4949517921780855 tu-c0r0n87

```


defe00: --Thermalizations 0 --Trajectories 1
defe01: --Thermalizations 5 --Trajectories 3
 
 
 Note: so far ran with --accelerator-threads 1; shall we run a few more case?

2025-02-03 10:12 UTC, asifsamiarain commented
In connection with congif1 `--grid 24.24.24.48 --mpi 1.1.1.1 --Trajectories 5 --Thermalizations 3`

develop branch:
```
[dc-asif1@tursa-login2 pgda018]$ mlc gdchk defe
                                                                        LOG_NAME             SEC                 Plaquette      NODES
              gd_tursa-gnucuda_001-008_mobi-24.24.24.48-1.1.1.1_defe00_45339.log    16758.760737        0.5974304307694565 tu-c0r4n21
              gd_tursa-gnucuda_001-008_prod-24.24.24.48-1.1.1.1_defe01_45012.log      170.332597         0.996634196056962 tu-c0r1n30
               gd_tursa-gnucuda_001-008_su3-24.24.24.48-1.1.1.1_defe02_45803.log     1977.824533        0.4949517921780855 tu-c0r0n72
```

and gague_actions_deriv branch:
```
[dc-asif1@tursa-login2 pgda019]$ mlc gdchk defe
                                                                        LOG_NAME             SEC                 Plaquette      NODES
              gd_tursa-gnucuda_001-008_mobi-24.24.24.48-1.1.1.1_defe00_44980.log    16761.844173        0.5974304307694565 tu-c0r1n24
              gd_tursa-gnucuda_001-008_prod-24.24.24.48-1.1.1.1_defe01_45113.log      150.759162         0.996634196056962 tu-c0r0n72
               gd_tursa-gnucuda_001-008_su3-24.24.24.48-1.1.1.1_defe02_45825.log     1829.613212        0.4949517921780855 tu-c0r0n72
```


In connection with config2 `--grid 32.32.32.64 --mpi 1.1.1.4 --Trajectories 5 --Thermalizations 3`

develop branch:
```
[dc-asif1@tursa-login2 pgda018]$ mlc gdchk deff
                                                                        LOG_NAME             SEC                 Plaquette      NODES
              gd_tursa-gnucuda_004-008_mobi-32.32.32.64-1.1.1.4_deff00_45340.log    17867.537452        0.5973682800185346 tu-c0r1n69
              gd_tursa-gnucuda_004-008_prod-32.32.32.64-1.1.1.4_deff01_44982.log      226.403670         0.996599127390424 tu-c0r1n27
               gd_tursa-gnucuda_004-008_su3-32.32.32.64-1.1.1.4_deff02_45802.log     2443.877700        0.4948530689679816 tu-c0r0n72
```

and gague_actions_deriv branch:
```
[dc-asif1@tursa-login2 pgda019]$ mlc gdchk deff
                                                                        LOG_NAME             SEC                 Plaquette      NODES
              gd_tursa-gnucuda_004-008_mobi-32.32.32.64-1.1.1.4_deff00_45011.log    17806.483462        0.5973682800185346 tu-c0r4n03
              gd_tursa-gnucuda_004-008_prod-32.32.32.64-1.1.1.4_deff01_45112.log      209.341596         0.996599127390424 tu-c0r0n72
               gd_tursa-gnucuda_004-008_su3-32.32.32.64-1.1.1.4_deff02_45814.log     2322.403084        0.4948530689679816 tu-c0r0n72
```

As expressed above by @qiUip at https://github.com/UCL-ARC/Grid/issues/15#issuecomment-2621663176, the `mobi `refer to the HMC/Mobius2p1f and `prod` to tests/smearing/Test_WilsonFlow. Additionally also gathered the results against tests/hmc/Test_hmc_WilsonFermionGauge referred as `su3`.

2025-02-14 19:05 UTC, RChrHill requested changes
The performance improvement that was discussed for this PR is good, but what has functionally changed about the code is obscured a little bit by the whitespace changes and swapping of variable names. I think to make what has been changed clearer, the whitespace changes should be reverted, which will declutter the PR and leave the most important information more visible. The variable name swapping also adds clutter to the PR, but it also improves the consistency of the code, so I think this is OK to keep.

Thanks for digging into this improvement -- I look forward to enjoying a speedier Grid in the future!

2025-02-14 19:05 UTC, RChrHill commented on Grid/qcd/action/gauge/PlaqPlusRectangleAction.h
> +    RealD factor_r = c_rect / RealD(Nc) * 0.5;
Changing the whitespace in the function signature is good because it makes it self-consistent. However, maybe we should avoid whitespace changes in the function body because it obscures the main functional changes of the PR a bit.

However, I think swapping the Umu <-> U naming convention is reasonable, because it makes it consistent with the naming convention of the return type.

2025-02-14 19:05 UTC, RChrHill commented on Grid/qcd/action/gauge/PlaqPlusRectangleAction.h
> +      Umu[mu] = PeekIndex<LorentzIndex>(U, mu);
Also revert whitespace changes here if reverting

2025-02-14 19:05 UTC, RChrHill commented on Grid/qcd/action/gauge/PlaqPlusRectangleAction.h
> +
Also revert whitespace changes here if reverting

2025-02-14 19:05 UTC, RChrHill commented on Grid/qcd/action/gauge/PlaqPlusRectangleAction.h
> -
I think this whitespace change is OK

2025-02-14 19:05 UTC, RChrHill commented on Grid/qcd/utils/WilsonLoops.h
Also revert whitespace changes here if reverting

2025-02-14 19:05 UTC, RChrHill commented on Grid/qcd/utils/WilsonLoops.h
>        }
Also revert whitespace changes here if reverting

2025-02-17 14:41 UTC, qiUip commented on Grid/qcd/utils/WilsonLoops.h
The reason for the whitespace changes here specifically was to make it easier to understand the nested functions calls for those of us less proficient with functional programming (this almost looks like lisp!).  We can revert it back, but I do think there is a case to be made for the changes to the whitespaces here.

2025-02-17 14:41 UTC, qiUip commented on Grid/qcd/utils/WilsonLoops.h
>        }
Same as comment on lines 321/322.

2025-02-17 16:36 UTC, RChrHill commented on Grid/qcd/utils/WilsonLoops.h
Personally I think I actually quite like the original whitespacing since (although it makes the lines very long) it does make it clear from the indentation which arguments are getting passed to which functions, to me at least. I would err on the side of minimalist changes for the PR, but I won't force the issue.

2025-02-17 17:36 UTC, qiUip commented on Grid/qcd/utils/WilsonLoops.h
I have no idea how these shorter lines with multiple tabs and splitting things over more line in the second case makes it more readable (I just tried to read the original and it's really confusing to me), but whatever is easier to get reviewed is fine with me!  The tabs in an empty line seem to be removed by GitHub automatically as I did try to leave them in...

2025-02-17 17:40 UTC, qiUip commented on Grid/qcd/action/gauge/PlaqPlusRectangleAction.h
> +
Done.  Only the tab on the empty line got removed automatically, hope that's okay.

2025-02-17 18:51 UTC, qiUip commented
Validated the checksums of the ckpoint files and they are still the same after the changes.  Merging this for our repo and will create a PR upstream without the patch tomorrow.

2025-02-17 18:52 UTC, merged